### ISSUE TITLE
Submit PR to strong-remoting to add support for application/vnd.api+json

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#41]
Should be a very simple change. Just need to add a case to switch statement that falls through to json.

See discussion here:
https://github.com/strongloop/loopback/issues/445#issuecomment-150923129

**Comment by digitalsadhu** [comment]
PR submitted here:
https://github.com/strongloop/strong-remoting/pull/249

**Comment by digitalsadhu** [comment]
PR Accepted, waiting for merge.
We should be able to remove setting the application/vnd.api+json response header once the PR is accepted.

**Comment by digitalsadhu** [comment]
Ok all merged. 

What this means:
So long as strong remoting is at v2.22.1 or greater, it should now be possible to set the header:
```json
"Accept": "application/vnd.api+json"
```
and the response header:
```json
"Content-Type": "application/vnd.api+json"
```
will automatically be set so long as `application/vnd.api+json` is in the list of supported types

**Comment by digitalsadhu** [comment]
**TODO:**
- [ ] Make sure components loopback/strong-remoting dependency up to v2.22.1
- [ ] Remove explicit setting of `Content-Type: application/vnd.api+json` in various places in the component
- [ ] Add README documentation that it is necessary to set `Accept: application/vnd.api+json` when using this component and that doing so will result in `Content-Type: application/vnd.api+json` being set on the response
- [ ] Ensure tests pass
- [ ] Manually test that this works
