### ISSUE TITLE
Relationship output with fetched data

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#48]
I thought I should probably spec out an issue on how this should work so we can write the relevant tests and implement.

When data is returned and there is no include filter used in the url to include related data, the relationships block should only return links informing the consumer where to fetch the actual data.

Example:
```js
"relationships":{  
  "category":{  
    "links": {
      "related": "http://localhost:3000/api/services/1/category"
    }
  }
}
```

When an include filter is used in the url, relationship links should be present but also the related data itself should be returned.

Example:
```js
"relationships":{  
  "category":{  
    "links": {
      "self": "http://localhost:3000/api/services/1/relationships/category", //<-- this also needs to be added when include filter is used
      "related": "http://localhost:3000/api/services/1/category"
    },
    "data": { "type": "category", "id": 2 }
  }
}
```

And an `included` top level key should also be included with the full data (side loading)

Example:
```js
"included":[  
  {"type": "category", "id": 2, "attributes": { "value": "green" }}
]
```

### TODO

- [x] Write tests to cover the above use cases
- [x] Complete "without include" filter implementation as detailed above
- [x] Complete "with include" filter implementation as detailed above
- [x] Rewrite loopback include syntax to meet JSON API expectations

**Comment by teckays** [comment]
I can't wait to have this!

**Comment by digitalsadhu** [comment]
@teckays nice!
@tsteuwer is working on this at the moment.

**Comment by tsteuwer** [comment]
Hey, @digitalsadhu, I didn't actually implement this part. I can take this ticket though once it goes into ``master`` since I know where everything is :D

**Comment by digitalsadhu** [comment]
Your branch gets a good chunk of this though I think? Just need to get the bit where the links to included resources gets made in the relationships block for each resource it looks like.

**Comment by digitalsadhu** [comment]
Merged into master as v0.11.0
Enjoy!
